### ISSUE TITLE
查询一条路径经过的所有城市这个例子有吗，好像没看到

### ISSUE THREAD

**Issue by LDXu** [xiangyuecn/AreaCity-Query-Geometry#1]
查询一条路径经过的所有城市这个例子有吗，好像没看到

**Comment by xiangyuecn** [comment]
用 QueryGeometry 方法查询，任意图形都支持，路径一般是用 LINESTRING

https://github.com/xiangyuecn/AreaCity-Query-Geometry/blob/bbcc9c12eeaa13f03ce5d2c13976dc8ce8598510/README.md?plain=1#L108-L110

**Comment by LDXu** [comment]
好的，多谢
